### PR TITLE
- Allows parsing from a string using :$xml named parameter

### PR DESCRIPTION
**Pull request by Xliff**

### CODE REVIEW

**Comment by MARTIMM** [comment]
I am not sure what you like to change; is it that you like to have an :xml named attribute added? Would perhaps be better to use multi BUILD's because there are already a few. saves some testing too.

**Comment by Xliff** [comment]
Well, currently you have to load the XML from a file. This is a bit inefficient when all of your documents exist in memory, so the new logic is there to make writing out to a file optional, or unnecessary. If you would prefer multiple BUILDs, then that's OK. I can reformat the PR with another commit.

**Comment by MARTIMM** [comment]
Ok, I'll accept the PR and rewrite it a bit and add some tests
Thanks for your work

**Comment by MARTIMM** [comment]
P.s. I can't email to you (Xliff) directly, so I do it here... I've seen on your github account that you're working on an gtk implementation p6-GtkPlus but not yet published yet. I am also working on a series of packages Gnome::Gtk3, Gnome::Gdk3 etc. I get the feeling of a 'reinventing the wheel' here. There were already a few smaller packages but I thought I wanted to get it more complete.
So, I thought, is it much different?

**Comment by Xliff** [comment]
@MARTIMM - Well, this started as a learning exercise for NativeCall, and has since become its own monstrocity. As far as 'reinventing the wheel', I am not adverse to having someone else out there working toward the same aim, especially if you are getting something out of your own work.

My p6-GtkPlus work is still a _hobby_ for me, although I hope to turn it into something more.

For what its worth, I think the best way to answer your question is for you to grab P6-GtkPlus and take a look for yourself. It started with me wanting to create an addon for GTK::Simple, since it has numerous limitations. It's then grown to cover much of GLib (currently testing GIO), GDK and GTK, I've also created several apps with it.

If you would like to collaborate on it, I would be more than grateful for your input. Even so. One of the best things about being Perl is that TIMTOWTDI. If you are looking for a specific design ethic to your code, I encourage you to pave your own path and continue with your work. If you think you could improve my project (or... me improve yours) then lets discuss things further!

**Comment by MARTIMM** [comment]
@Xliff 
Yes - Just like you, I wanted to do more with native calls, with examples from GTK::Simple. It is growing big too. I thought not to do too much from GIO because Perl6 has a lot of tools to do IO. But Pango and Cairo is referenced quite a few times from GTK so that I need to implement. I skip those classes and subs which are deprecated in GTK. A few classes, like GtkMisc, I've kept because of the inheritance  tree which I wanted to keep.

I've already taken a peek at your software and have seen that the setup is different. I think its more compact. Also you already have so many classes defined that I grow a bit jaleous. But like you've said there are more ways to do things. I will look into it more carefully, I surely can learn a thing or two.

I've created a program which helps me generating a perl module from the gtk sources. it has documentation included from those sources. After generating I need to inspect the result, because not everything is correct. Sometimes the result need other classes which are not implemented yet and have to comment the subs out. Mostly Pango and Cairo.

All native subs are declared in classes where they belong and not in one large file like in GTK::Simple. Then I use the FALLBACK mechanism at the top which start search in the inheritance tree at the bottom to find the subs. The interface modules are queried in the same way but more like a side step. This way, it looks like the class has all methods in it whithout having to declare them.

Some of the subs are rewritten to return data in a list. This mecanism lets the user use the standard perl types instead of the native types which are needed to return data in the argument list. Also a few subs use variable argument lists. These needed a rewrite too.

All signal types will be supported in the next version. I recently found a mechanism to handle variable argument lists in the signal handlers. Now I am rewriting the modules I already have before continuing writing new ones.

Using a Glade generated XML, one can build a user interface with all bells and wistles without having the classes available. It helps me then to concentrate on the most useful ones and then later add the less used ones. Available classes can also be instantiated using an id from that generated XML by GtkBuilder. 

All documentation is put on the [github pages](https://martimm.github.io/perl6-gnome-gtk3/). I'm also trying to keep a test coverage on the software so that it will be visible how much is tested. Next to the document references I wanted to show a tutorial as well as examples on that site.

So a lot needs to be done yet and I'm curious where our projects will lead us.

**Comment by Xliff** [comment]
I am as well. There may be one place where I can at least be a guide, and additionally a bit of a help! See my [p6-Pango](https://github.com/Xliff/p6-Pango) project for hints on how to get Pango working properly. Now, the one test I _cannot_ seem to get working is [here](http://github.com/Xliff/p6-Pango/issue/2). I haven't yet had much time to go over it, but I suspect there is a bug there.  For reference, [the original C code is here](https://github.com/GNOME/pango/blob/master/examples/cairotwisted.c).

If you have some time and can try your own hand at it, especially if you reach that point with your own Pango project, I'd be interested to know your thoughts!

**Pull request merged**
